version: "3"

services:
  node:
    build:
      dockerfile: ./deno-qa/Dockerfile
      context: ./..
    image: flagship-ts-sdk:deno-qa
    container_name: deno-qa
    ports:
      - 8000:3000
    tty: true
