version: "3"

services:
  deno-v-latest:
    build:
      dockerfile: flagship/demo/deno/Dockerfile
      context: ../../../
    image: flagship-ts-sdk:deno-test-latest
    container_name: deno-test-version-latest
    tty: true
  deno-v-1.10.3:
    build:
      dockerfile: flagship/demo/deno/Dockerfile-1.10.3
      context: ../../../
    image: flagship-ts-sdk:deno-test-v-1.10.3
    container_name: deno-test-version-1.10.3
    tty: true