export { Event, EventCategory } from './Event'
export type { IEvent } from './Event'
export { Item } from './Item'
export type { IItem } from './Item'
export { Page } from './Page'
export type { IPage } from './Page'
export { Screen } from './Screen'
export type { IScreen } from './Screen'
export { Transaction } from './Transaction'
export type { ITransaction } from './Transaction'
export { HitAbstract } from './HitAbstract'
export type { IHitAbstract } from './HitAbstract'
export type { HitShape } from './Legacy'
export type { IConsent } from './Consent'
export { Consent } from './Consent'

export { Campaign } from './Campaign'
export type { ICampaign } from './Campaign'

export { Segment } from './Segment'
export type { ISegment } from './Segment'
