name: CI

on:
  push:
    branches: [main, node]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
        
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v1
      - run : ls
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
        working-directory: ./flagship
      - run: yarn install
      - run: yarn test
