name: Test

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      FS_API_KEY: "${{ secrets.FS_CI_CAMPAIGNS_API_KEY }}"
      FS_ENV_ID:  "${{ secrets.FS_CI_CAMPAIGNS_ENV_ID }}"
    defaults:
      run:
        working-directory: ./flagship
        
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn install
      - run: yarn lint
      - run: yarn test --coverage
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - run: yarn build-prod
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: build deno module
      

