name: NPM CD
on:
  push:
    tags: 
      - 2.3.1-alpha.*
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flagship
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm unpublish @flagship.io/js-sdk@2.3.1-beta.1
      - run: npm unpublish @flagship.io/js-sdk@2.3.1-beta.2
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}