name: NPM CD ALPHA
on:
  push:
    tags: 
      - "[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      FS_API_KEY: "${{ secrets.FS_CI_CAMPAIGNS_API_KEY }}"
      FS_ENV_ID:  "${{ secrets.FS_CI_CAMPAIGNS_ENV_ID }}"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn test --coverage
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - run: yarn build-prod
      - run: npm publish --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
